### ISSUE TITLE
Using schema registry with basic auth

### ISSUE THREAD

**Issue by alberttwong** [Dabz/kafka-security-playbook#81]
I'm using https://github.com/Dabz/kafka-security-playbook/tree/master/schema-registry/with-basic-auth and getting the following warning.

```
schema-registry-1  | [2024-07-25 16:05:27,150] WARN The configuration 'replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,150] WARN The configuration 'listeners' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,150] WARN The configuration 'topic.replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'confluent.license.replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'authentication.realm' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'confluent.schema.registry.authorizer.class' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'authentication.method' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'confluent.schema.registry.auth.mechanism' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'opts' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'kafkastore.topic.replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'host.name' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'authentication.roles' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'kafkastore.bootstrap.servers' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] WARN The configuration 'schema.registry.resource.extension.class' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
schema-registry-1  | [2024-07-25 16:05:27,151] INFO Kafka version: 7.0.15-ce (org.apache.kafka.common.utils.AppInfoParser)
```

Any ideas?

**Comment by alberttwong** [comment]
```
  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.15
    ports:
     - 8181:8181
     - 8081:8081
    environment:
     - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:29092
     - SCHEMA_REGISTRY_HOST_NAME=schema-registry
     - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
     - SCHEMA_REGISTRY_AUTHENTICATION_METHOD=BASIC
     - SCHEMA_REGISTRY_AUTHENTICATION_ROLES=write,read,admin
     - SCHEMA_REGISTRY_AUTHENTICATION_REALM=Schema
#     - SCHEMA_REGISTRY_CONFLUENT_LICENSE_REPLICATION_FACTOR=1
     - SCHEMA_REGISTRY_OPTS=-Djava.security.auth.login.config=/tmp/jaas_config.file
#     - SCHEMA_REGISTRY_SCHEMA_REGISTRY_RESOURCE_EXTENSION_CLASS=io.confluent.kafka.schemaregistry.security.SchemaRegistrySecurityResourceExtension
#     - SCHEMA_REGISTRY_CONFLUENT_SCHEMA_REGISTRY_AUTHORIZER_CLASS=io.confluent.kafka.schemaregistry.security.authorizer.schemaregistryacl.SchemaRegistryAclAuthorizer
#     - SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR=1
#     - SCHEMA_REGISTRY_CONFLUENT_SCHEMA_REGISTRY_AUTH_MECHANISM=JETTY_AUTH
    volumes:
      - ./jaas_config.file:/tmp/jaas_config.file
      - ./password-file:/tmp/password-file
```

```
albert@Alberts-MacBook-Pro mysql-debezium % cat register-mysql-avro.json
{
    "name": "inventory-connector",
    "config": {
        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
        "tasks.max": "1",
        "database.hostname": "mysql",
        "database.port": "3306",
        "database.user": "debezium",
        "database.password": "dbz",
        "database.server.id": "184054",
        "topic.prefix": "dbserver1",
        "database.include.list": "inventory,pets",
        "schema.history.internal.kafka.bootstrap.servers": "kafka:29092",
        "schema.history.internal.kafka.topic": "schema-changes.inventory",
        "key.converter.basic.auth.credentials.source": "USER_INFO",
        "key.converter.basic.auth.user.info": "admin:admin",
        "value.converter.basic.auth.credentials.source": "USER_INFO",
        "value.converter.basic.auth.user.info": "admin:admin",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "key.converter.schema.registry.url": "http://schema-registry:8081",
        "value.converter.schema.registry.url": "http://schema-registry:8081"
    }
}
```
